# Server Configuration
server.port=8080

# Application Metadata
spring.application.name=careerhub-platform

# Default Datasource - In-Memory H2 Database
spring.datasource.url=jdbc:h2:mem:careerhubdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# H2 Console Configuration
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=true

# JPA & Hibernate Settings
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

# Multipart Upload Size Limits (For Resume Uploads)
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB

# Mail properties (Simulated by default)
spring.mail.host=localhost
spring.mail.port=25
spring.mail.properties.mail.smtp.auth=false
spring.mail.properties.mail.smtp.starttls.enable=false

# App specific JWT properties
app.jwtSecret=dGhpcy1pcy1hLXNlY3VyZS1zZWNyZXQta2V5LXRvLWJlLXVzZWQtZm9yLWNhcmVlcmh1Yi1tdnAtYXBwbGljYXRpb24=
app.jwtExpirationInMs=86400000
