# Server Configuration
server.port=8080

# Application Metadata
spring.application.name=careerhub-platform

# Default Datasource - In-Memory H2 Database
spring.datasource.url=jdbc:mysql://localhost:3306/db_careerhub?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver

# H2 Console Configuration
spring.h2.console.enabled=false

# JPA & Hibernate Settings
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# Multipart Upload Size Limits (For Resume Uploads)
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB

# Mail properties (Simulated by default)
spring.mail.host=localhost
spring.mail.port=25
spring.mail.properties.mail.smtp.auth=false
spring.mail.properties.mail.smtp.starttls.enable=false

# App specific JWT properties
app.jwtSecret=${JWT_SECRET:dGhpcy1pcy1hLXNlY3VyZS1zZWNyZXQta2V5LXRvLWJlLXVzZWQtZm9yLWNhcmVlcmh1Yi1tdnAtYXBwbGljYXRpb24=}
app.jwtExpirationInMs=86400000
